
```{r}
library(maps)
library(mapdata)
library(dplyr)
library(ggplot2)
library(mapplots)
```

```{r}
map(database = 'county')
map(database = 'world', region = 'south korea')
map('world2Hires', 'South Korea') 
```

```{r}
data("us.cities")
head(us.cities)
```

```{r}
map('state', 'Georgia')
map.cities(us.cities, country = 'GA')
```

```{r}
map('world', fill = T, col = rainbow(1627))
```

```{r}
data(unemp) # unemployed rate data
data(county.fips) # county fips data
head(unemp,3)
head(county.fips)
```

```{r}
unemp$colorBuckets <- as.numeric(cut(unemp$unemp, c(0, 2, 4, 6, 8, 10, 100)))
colorsmatched <- unemp$colorBuckets[match(county.fips$fips, unemp$fips)]
library(mapproj)
colors = c("#F1EEF6","#D4B9DA","#C994C7","#DF65B0","#DD1C77","#980043")
map("county", col = colors[colorsmatched], fill = TRUE, resolution = 0, lty = 0, projection = 'polyconic')

#colorsmatched[1]
#county.fips[1,]
#unemp[1,]
```

```{r}
wm = map_data('world')

ur <- wm %>% dplyr::select(region)%>%unique()
grep( "Korea", ur$region )

map("world", ur$region[c(125,185)],fill = T, col = "blue")
abline(h=38)
#points(x=37.51974777, y = 126.85398553, pch=9, col = 'red')


## <LAT>37.51974777</LAT>
## <LNG>126.85398553</LNG>
```
```{r}
#pie chart on map
library(mapplots)
library(ggmap)
map('worldHires', 'South Korea')
seoul_loc = geocode('seoul')
busan_loc = geocode('Busan')
add.pie(z=c(1,4,6),labels = c('a','b','c'), 
        x = seoul_loc$lon, y = seoul_loc$lat, radius = 0.8)
add.pie(z=4:3,labels = c('a','b'),
        x = busan_loc$lon, y = busan_loc$lat, radius = 0.5)
```

