```{r}
library(dplyr)
library(ggplot2)
raw_data = read.csv('d:/cns_data/filtered_raw_data.csv')[,-1]

```

```{r}

raw_data = raw_data[,c(1,6,7,2,8,9,11:13,3,4,10,5)]
colnames(raw_data) = c('date', 'UPC', 'prod_name', 'promotion', 'volume', 'sales', 'promo_info', 'promo_title', 'promo_detail', 'brand', 'line', 'BM', 'type')
raw_data = raw_data %>% mutate('s/v' = as.integer(sales/volume))
raw_data = raw_data[,c(1:6,14,7:13)]
#raw_data %>% filter(volume<=0) %>% filter(sales>=0)
#raw_data = raw_data %>% filter(BM != '기타/판촉')
raw_data[(raw_data$promotion=='비할인행사'& is.na(raw_data$promo_info)), ]$promotion = '비행사제품(추정)'
raw_data = raw_data[-which(raw_data$UPC==30100095)[seq(1, length(which(raw_data$UPC==30100095)), by=2)],]
raw_data$date = as.Date(raw_data$date)

#write.csv(raw_data, 'd:/cns_data/raw_data.csv')
raw_data
```


```{r}
upc = raw_data %>% group_by(UPC) %>% tally() %>% arrange(desc(n))
for(i in 1:nrow(upc)){
  upc[i,3] = as.Date(unclass(raw_data %>% filter(UPC==unclass(upc[i,1])) %>% summarize(min(date)))$'min(date)',origin="1970-01-01")
  #upc[i,3] = as.Date(unclass(upc[i,3])$dates,origin="1970-01-01")
  upc[i,4] = as.Date(unclass(raw_data %>% filter(UPC==unclass(upc[i,1])) %>% summarize(max(date)))$'max(date)',origin="1970-01-01")
  #upc[i,4] = as.Date(upc[i,3],origin="1970-01-01")
  upc[i,5] = upc[i,4]-upc[i,3]+1
  }
upc$V3 = as.Date(upc$V3, origin = '1970-01-01')
upc$V4 = as.Date(upc$V4, origin = '1970-01-01')
upc = upc %>% mutate(if_else(V4.1>n,'F','T'))
upc = upc[,c(1,6,2:5)]
colnames(upc)[2:6] = c('test', 'n', 'start', 'end', 'duration')

upc$unique_dates = NA
for (i in 1:nrow(upc)){
  a = raw_data %>% filter(UPC == unclass(upc[i,1])$UPC)
  upc[i,7] = length(unique(a$date))
  upc[i,2] = if_else(upc[i,3]==upc[i,6] & upc[i,6]==upc[i,7], 'T', 'F')
  rm(a)
}


upc

#write.csv(upc, 'd:/cns_data/upc_durations.csv')
#upc %>% filter(n==duration)
upc %>% filter(test =='T')
```

```{r}
dt = read.csv('d:/cns_data/raw_data_dt.csv')

```

```{r}

```

