```{r}
data <- read.csv('./data.csv', header=T, stringsAsFactors = F)

str(data)

data <- data[,-c(8,9,10,11,12,13,14,15,22,23,24,25,26,27)]

head(data)

rowname <- data[,1]

data <- data[,-1]

row.names(data) = rowname[]

str(data)

library(cluster)
data2 <- scale(data)

# ward
hc.ward=hclust(dist(data2), method="ward.D")# 완전연결 ( 최대 클러스터간 비유사성)
plot(hc.ward, main = 'ward linkage Clustering') 

x <- cutree(hc.ward, 3) # 3개의 클로스터로 덴드로그램을 절단한다
x

mds = cmdscale(dist(data2), k = 2)
plot(mds, col = x)

mean.ward1 = data.frame(colMeans(data2[x==1,]))
mean.ward2 = data.frame(colMeans(data2[x==2,]))
mean.ward3 = data.frame(colMeans(data2[x==3,]))

mean.ward = data.frame(mean.ward1, mean.ward2, mean.ward3)
names(mean.ward) = c(1:3)
mean.ward

```

```{r}
coord = read.csv('./road_coord.csv')
coord = coord[,-1]

coord_by_group = merge(coord,cbind(road_name = names(x), x), by = 'road_name')
names(coord_by_group) = c('road_name', 'x', 'y', 'group')
```

```{r}
library(ggmap)
library(RColorBrewer)
# 서울 기준 open street map 호출
SeoulMap = qmap("seoul", zoom = 11, scale = 4, maptype = "toner-lite", source= 'stamen', legend = "topleft", extent = 'device', size = c(1280,1280))
```

```{r}
road_map = SeoulMap +
  geom_point(aes(x = x, y = y, col = group), data = coord_by_group, size =4) + 
  coord_equal()

road_map
```

```{r}
kmeans2 = kmeans(data2, centers = 4)

mean.k21 = data.frame(colMeans(data2[kmeans2$cluster==1,]))
mean.k22 = data.frame(colMeans(data2[kmeans2$cluster==2,]))
mean.k23 = data.frame(colMeans(data2[kmeans2$cluster==3,]))
mean.k24 = data.frame(colMeans(data2[kmeans2$cluster==4,]))

mean.kmeans2 = data.frame(mean.k21, mean.k22, mean.k23, mean.k24)

kmeans2$cluster
```

```{r}
coord_by_group2 = merge(coord,cbind(road_name = names(kmeans2$cluster), kmeans2$cluster), by = 'road_name')
names(coord_by_group2) = c('road_name', 'x', 'y', 'group')
```

```{r}
road_map = SeoulMap +
  geom_point(aes(x = x, y = y, col = group), data = coord_by_group2, size =4) + 
  coord_equal()

road_map
```

```{r}
library(dplyr)
kmeans_data = cbind(data,'cluster' = as.factor(kmeans2$cluster))
kcluster = as.factor(kmeans2$cluster)
k1 = kmeans_data[kcluster==1,][,-19]
k2 = kmeans_data[kcluster==2,][,-19]
k3 = kmeans_data[kcluster==3,][,-19]
k4 = kmeans_data[kcluster==4,][,-19]


k1m =round(apply(k1, 2, mean),2)
k2m =round(apply(k2, 2, mean),2)
k3m =round(apply(k3, 2, mean),2)
k4m =round(apply(k4, 2, mean),2)

kmdata = data.frame(k1m,k2m,k3m,k4m)

write.csv(kmdata,'kmdata.csv')
write.csv(coord_by_group2,'g2.csv')
```

```{r}
k1
```

```{r}
##cluster = 4
set.seed(1)
kmeans2 = kmeans(data2, centers = 4, nstart = 25)
data.frame(kmeans2$cluster)
mean.k21 = data.frame(colMeans(data2[kmeans2$cluster==1,]))
mean.k22 = data.frame(colMeans(data2[kmeans2$cluster==2,]))
mean.k23 = data.frame(colMeans(data2[kmeans2$cluster==3,]))
mean.k24 = data.frame(colMeans(data2[kmeans2$cluster==4,]))

mean.kmeans2 = data.frame(mean.k21, mean.k22, mean.k23, mean.k24)
View(mean.kmeans2)

a = data.frame(colMeans(data[kmeans2$cluster==1,]))
b = data.frame(colMeans(data[kmeans2$cluster==2,]))
c = data.frame(colMeans(data[kmeans2$cluster==3,]))
d = data.frame(colMeans(data[kmeans2$cluster==4,]))
options(scipen = 999)
mean = data.frame(a, b, c, d)
View(mean)
```

