```{r}
library(arules)
library(datasets)
 
# Load the data set
data(Groceries)
str(Groceries)
```

```{r}
Groceries@itemInfo
```

```{r}
Groceries@data[,1:100]  # the first 100 baskets
image(Groceries@data[,1:100])
```

```{r}
# Create an item frequency plot for the top 20 items
itemFrequencyPlot(Groceries,topN=20,type="absolute")
```

```{r}

# Get the rules
rules = apriori(Groceries, parameter = list(supp = 0.001, conf = 0.8))
library(arulesViz)
plot(rules)
```

```{r}
#plot(rules,method="graph",interactive=TRUE,shading=NA)
plot(rules[1:10],method="graph",engine = 'interactive',shading=NA)
```

```{r}
# Show the top 5 rules, but only 2 digits
options(digits=2)
inspect(rules[1:5])
```

```{r}
rules<-sort(rules, by="confidence", decreasing=TRUE)
inspect(rules[1:5])
```

```{r}
rules<-apriori(data=Groceries, parameter=list(supp=0.001,conf = 0.08), 
               appearance = list(default="lhs",rhs="bottled beer"),
               control = list(verbose=F))
rules<-sort(rules, decreasing=TRUE,by="confidence")
inspect(rules[1:5])
```

