```{r}
library(xlsx)
data = read.xlsx('./data_set.xlsx', encoding = 'UTF-8', sheetIndex = 1)
coord = read.csv('./road_coord.csv')
coord = coord[,-1]
```

```{r}
data = merge(data,coord, by = 'road_name')
```

```{r}
library(ggmap)
library(RColorBrewer)
# 서울 기준 open street map 호출
SeoulMap = qmap("seoul", zoom = 11, scale = 4, maptype = "toner-lite", source= 'stamen', legend = "topleft", extent = 'device', size = c(1280,1280))

```
```{r}
data
```

```{r}
kdata = kmeans(data[,2:23], centers = 4)
```

```{r}
data = cbind(data,kdata$cluster)
```

```{r}
map1 = SeoulMap +
  geom_point(aes(x = x, y = y, col = kdata$cluster), data = coord_by_group, size =4) + 
  coord_equal()


map1
```

```{r}
mds = cmdscale(dist(data[-19,2:23]), k = 2)
plot(mds, col = kdata$cluster)
```

```{r}
dongil = read.csv('동일로.csv')
names(dongil) = c('y', 'x')
dongil = arrange(dongil, desc(y))
```


```{r}
map1 = SeoulMap +
  #ggplot(aes(x = x, y = y), data = dongil, size =1) +
  #geom_point(aes(x = x, y = y), data = dongil, size =1) + 
  geom_path(aes(x = x, y = y), data = dongil, size =2) +
  #geom_density2d(aes(x = y, y = x, alpha = 0), bins = 1, data = dongil) +
  coord_equal()

map1
```