```{r}
library(MASS)
```

```{R}
### 상관계수 그래프
Omega  = matrix(c(1,0,0.5,
                  0,1,0.3,
                  0.5,0.3,1)
                ,3,3)

Sigma <- solve(Omega)
n = 100
pcor.vec <- rep(0,1000)
for ( i in 1:1000)
{
  rdata<-mvrnorm(n,mu = rep(0,3), Sigma)
  x = rdata[,1]
  y = rdata[,2]
  z = rdata[,3]
  
  x = x-mean(x)
  y = y-mean(y)
  z = z-mean(z)
  
  pcor.vec[i]<-cor(lm(x~z-1)$residual,lm(y~z-1)$residual)
  
}

boxplot(pcor.vec)
```

```{r}
### 편상관계수 그래프
library(igraph)

Sigma  = matrix(c(1,0,0.5,
                  0,1,0.3,
                  0.5,0.3,1)
                ,3,3)
Sigma.cov <- Sigma
Sigma.cov[Sigma>0] <- 1
diag(Sigma.cov) <- 0
ed <- graph_from_adjacency_matrix(Sigma.cov, mode='undirected')
plot(ed)

adjm <- matrix(sample(0:1, 100, replace=TRUE, prob=c(0.9,0.1)), 10,10)
g1 <- graph_from_adjacency_matrix( adjm )
plot(g1)



Sigma  = matrix(c(1,0,0.5,0,
                  0,1,0.3,0.2,
                  0.5,0.3,1,0,
                  0,0.2,0,1)
                ,4,4)
Sigma11<- Sigma[1:2,1:2]
Sigma12<- Sigma[1:2,3:4]
Sigma21<- Sigma[3:4,1:2]
Sigma22<- Sigma[3:4,3:4]

tmp<-Sigma11 - Sigma12%*%solve(Sigma22)%*%Sigma21

tmp[1,2]/sqrt(tmp[1,1]*tmp[2,2]) #Partial Correlation
solve(Sigma)



Omega  =matrix(c(1,0,0.5,0.1,
                 0,1,0.3,0.2,
                 0.5,0.3,1,0,
                 0.1,0.2,0,1)
               ,4,4)
Omega[Omega!=0] <- 1
diag(Omega) <- 0
ed <- graph_from_adjacency_matrix(Omega, mode='undirected')
plot(ed)
```

```{r}
library(glasso)
x<-matrix(rnorm(50*20),ncol=20)
s<- var(x)
a<-glasso(s, rho=.01)
aa<-glasso(s,rho=.02, w.init=a$w, wi.init=a$wi)
aa$wi
image(aa$wi)
```

